### ISSUE TITLE
Errors?

### ISSUE THREAD

**Issue by greggman** [renan/powerdns-docker#1]
Not sure if you care but I ran your stuff

```
docker-compose stop   # not really needed first time but did anyway 
docker-compose rm     # not really needed first time but did anyway
docker-compose build
docker-compose up
```

Saw errors about powerdns unable to connect to mysql but it would try again on query

Tried 

```
dig example.local @$DOCKER_IP
```

I see the query come in but I get this

```
authoritative_1 | Apr 02 09:51:12 Backend error: GSQLBackend lookup query:Failed to execute mysql_query, perhaps connection died? Err=1: Table 'powerdns.records' doesn't exist
```

I tried

```
docker-compose build
docker-compose up
```

The errors about powerdns not being able to connect went away but still get that error

**Comment by renan** [comment]
This code ain't really production-ready yet, not even close to that. But I do care if people fail to use my work. :)

Anyways... For me the problem was:

```
authoritative_1 | ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (111)
```

The database container was taking too long to initialize, for now I have increased the sleep time as you can see in the commit. Let me know if that works for you?
